### ISSUE TITLE
Question about the generated output

### ISSUE THREAD

**Issue by mahmoodn** [jseidl/GoldenEye#20]
For a test of a server with 2 cpus and 4G ram, I run the script with 2 workers. The output is

```
GoldenEye v2.1 by Jan Seidl <jseidl@wroot.org>

Hitting webserver in mode 'get' with 2 workers running 500 connections each. Hit CTRL+C to cancel.
Starting 2 concurrent workers
Initiating monitor
Starting worker Striker-2
Starting worker Striker-3
Process Striker-3:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "goldeneye.py", line 337, in run
    conn_req.request(method.upper(), url, None, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1017, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1051, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
Process Striker-2:
  File "/usr/lib64/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 807, in connect
Traceback (most recent call last):
    self.timeout, self.source_address)
  File "/usr/lib64/python2.7/socket.py", line 571, in create_connection
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    raise err
    self.run()
  File "goldeneye.py", line 337, in run
error: [Errno 111] Connection refused
    conn_req.request(method.upper(), url, None, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1017, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1051, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 807, in connect
    self.timeout, self.source_address)
  File "/usr/lib64/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused
0 GoldenEye strikes hit. (2 Failed)
0 GoldenEye strikes hit. (2 Failed)
0 GoldenEye strikes hit. (2 Failed)
0 GoldenEye strikes hit. (2 Failed)
Shutting down GoldenEye

```

I also noticed that the CPU usage caused by httpd is 100% while there are free ram on the server. Does that mean, the number of cpus are insufficient?

**Comment by jseidl** [comment]
Yes, if you're topping either your CPUs or Mem, means either your concurrency and/or worker count is too high for the given hardware, also `connection refused` means that something is not right (connectivity issues, server-side blocking etc)
