### ISSUE TITLE
GoldenEye strikes all fail

### ISSUE THREAD

**Issue by sku11-coder** [jseidl/GoldenEye#27]
![ddos fail](https://user-images.githubusercontent.com/61753674/76658410-143cd780-6542-11ea-883d-aeab23405e43.PNG)
no attack lands, ive tried this multiple times minimizing the workers and sockets and still

**Comment by alexdieu** [comment]
It’s a https website 
The website is using a crypted connexion
Tell me winch site is it and i Will take Down it 
Or you can try hammer or do à scan vunerability With dvwan vargant or nessus

**Comment by pablanco** [comment]
I'm facing a similar issue, any ideas?

```
$ python3 ./goldeneye.py http://127.0.0.1/ -w 1 -s 10 -n -d

GoldenEye v2.1 by Jan Seidl <jseidl@wroot.org>

Hitting webserver in mode 'get' with 1 workers running 10 connections each. Hit CTRL+C to cancel.
Starting 1 concurrent workers
Initiating monitor
Starting worker Striker-2
Process Striker-2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "./goldeneye.py", line 324, in run
    (url, headers) = self.createPayload()
  File "./goldeneye.py", line 357, in createPayload
    req_url, headers = self.generateData()
  File "./goldeneye.py", line 395, in generateData
    http_headers = self.generateRandomHeaders()
  File "./goldeneye.py", line 465, in generateRandomHeaders
    nrEncodings = random.randint(1,len(acceptEncoding)/2)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/random.py", line 222, in randint
    return self.randrange(a, b+1)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/random.py", line 195, in randrange
    raise ValueError("non-integer stop for randrange()")
ValueError: non-integer stop for randrange()
0 GoldenEye strikes hit. (1 Failed)
0 GoldenEye strikes hit. (1 Failed)
0 GoldenEye strikes hit. (1 Failed)
Shutting down GoldenEye
```

Thanks!

**Comment by royoan** [comment]
@pablanco  I try modify the 465 line in goldeneye.py
    nrEncodings = random.randint(1,len(acceptEncoding)/2)
modify to :
    nrEncodings = random.randint(1, int(len(acceptEncoding)/2))

Then its OK

**Comment by kamikazaliba01** [comment]
Tks, it's working now

**Comment by jseidl** [comment]
Just merged https://github.com/jseidl/GoldenEye/pull/29 fixing this
